FROM php:fpm-alpine3.20

RUN apk update && apk add --no-cache \ 
    icu-dev \
    curl \
    libxml2-dev \
    php-pdo_mysql \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl pdo_mysql mysqli

CMD [ "bin/cake", "server", "--host", "0.0.0.0", "--port", "8765" ]
