services:
    nginx:
        container_name: hyp0th3rapy-nginx
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./cms:/var/www/html"
        ports:
            - "80:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - db
        # networks:
        #     - web
    php:
        container_name: hyp0th3rapy-php
        build:
            context: .
            dockerfile: Dockerfile.backend
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./cms:/var/www/html"
        user: root:root
        # networks:
        #     - web
        #     - mysql_backend
    composer:
        container_name: hyp0th3rapy-composer
        build:
            context: .
            dockerfile: Dockerfile.composer
        volumes:
            - "./cms:/app"
            - "./etc/php/composer.ini:/usr/local/etc/php/php-cli.ini"
        command: install
        ports:
            - 7070
    db:
        image: mysql:${MYSQL_VERSION}
        container_name: hyp0th3rapy-mysql
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        # networks:
        #     - mysql_phpmyadmin
        #     - mysql_backend
    phpmyadmin:
        image: phpmyadmin
        restart: always
        container_name: hyp0th3rapy-phpmyadmin
        environment:
            - PMA_HOSTS=db
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - "8080:80"
        depends_on:
            - db
        # networks:
        #     - mysql_phpmyadmin
        #     - web

# networks:
#     mysql_phpmyadmin:
#         driver: bridge
#         ipam:
#             config:
#             - subnet: 10.5.0.0/24
#     mysql_backend:
#         driver: bridge
#         ipam:
#             config:
#             - subnet: 10.6.0.0/24
#     web:
#         driver: bridge
#         ipam:
#             config:
#             - subnet: 10.7.0.0/24

volumes:
    db_data: